apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deployment
  labels:
    app: fortune
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fortune
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - image: smokecookie/fortuneloop
        name: html-generator  # 명언을 만들어내는 컨테이너
        volumeMounts:
        - name: html
          mountPath: /var/htdocs  # 우리가 설정한 경로와 관련
      - image: nginx:alpine
        name: web-server  # 명언을 읽는 컨테이너
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html  # nginx에서 사용하는 디폴트 root document경로
          readOnly: true
        ports:
          - containerPort: 80
            protocol: TCP
      volumes:
      - name: html
        emptyDir: {}