apiVersion: v1
kind: Service
metadata:
  name: node-lb
spec:
  type: LoadBalancer  # lb 로드밸런서
  ports:
  - port: 80  # 입력받을 포트
    targetPort: 8080  # 받은 포트를 보낼 곳
  selector:
    app: nodeapp-pod  
    # label key: app, val: ndoeapp-pod를 선택
    # app.js의 서비스 포트가 8080임